### ISSUE TITLE
Several problems while trying to "install" and "start"

### ISSUE THREAD

**Issue by JustMeLC** [slead/React-ArcGIS-boilerplate#1]
1) Two (2) vulnerabilities found during npm install

2) Upon running npm start - received "Error: Cannot find module 'uglifyjs-webpack-plugin".  Added plugin as devDependency, now four (4) vulnerabilities found. npm audit fix not ran.

3) Reran npm start - now receive error below:

       ERROR in ./src/index.js
       Module build failed (from ./node_modules/babel-loader/lib/index.js):
       SyntaxError: D:\WebDev\ESRI\Frameworks\React\React-ArcGIS-boilerplate-master\src\index.js: Support for the experimental 
       syntax 'jsx' isn't currently enabled (7:8):

       5 | 
       6 | const rootElement = document.getElementById("root");
       7 | render(<WebMap className="viewDiv"/>, rootElement);
         |        ^
       8 |

**Comment by slead** [comment]
after I started this project, I came across this one, which is probably a better place to start: https://github.com/odoe/jsapi-react

so I'll probably delete this repo and use Rene's instead for future React/ArcGIS projects
